# org.gradle.jvmargs=-Xmx1536M
# android.useAndroidX=true
# android.enableJetifier=true
# kotlin.code.style=official


# AGP 8+ compatibility
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# Gradle optimizations
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
